site_name: Pictolines
theme:
  name: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - abbr
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Code Reference:
        - utils: docs-utils.md
    - References: references.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aitorig/pictolines
      name: GitHub repository

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js